### ISSUE TITLE
Space Mining

### ISSUE THREAD

**Issue by langelusse** [SWG-Source/client-assets#14]
Space Mining doesn't work. 

He indicate me "Your Weapon is ammo"

https://cdn.discordapp.com/attachments/725823232854327427/891736876791263272/IMG_20210926_192351.jpg

Guide: https://swg.fandom.com/wiki/Space_mining

**Comment by langelusse** [comment]
Ok we need to add this: thanks Ma'tar

[https://cdn.discordapp.com/attachments/366560008608940035/892151339847671938/ship_weapon_components.iff](url)

**Comment by Cekis** [comment]
To add to this... the file @langelusse links is the server version of the file.  That file makes mining work correctly, which means, the client side file is not in sync with the server version.  The proper fix is to ensure the client version that is being used (figure out which TRE file has the bad version - likely our custom one - and replace that file with the server's version OR the updated client version that contains the properly fixed file).  What's important to note is that the client side file from final day is CORRECT.  However, there's clearly a client TRE that is overwriting that one which is missing stuff or has incorrect stuff in it.

**Comment by langelusse** [comment]
For me Swgsource3_0.tre work but he is ecrased by patch_58_shared_00.tre. We need to add this files directly inside folder's

**Comment by Cekis** [comment]
The folders in the client are a final override.  Anything in those folders will override ANY TRE file you have in your client.  The real solution is to make sure our custom TRE file has the correct version of ship_weapon_components.iff.  Considering we added Space GCW and a few of the TCG craft since Patch 58, it may be considerably out of sync.

**Comment by langelusse** [comment]
Custom tre work for me so we need modify live.cfg and add this custom tre

**Comment by AconiteX** [comment]
This has been patched via 710acb52 from the IFF built by @langelusse. It will be packaged into the 3.1 tre when it is released and will be in the override directory path in the meantime.
