### ISSUE TITLE
[Tatooine] Darklighter Mission Missing Strings

### ISSUE THREAD

**Issue by CodeOfTheRing** [SWG-Source/client-assets#2]
Darklight Mission on Tat is missing Terminal 1 & 2 strings.

It calls quest\ground\legacy_button_reb_darklighter. Terminals 3,4,5 don't have this issue.
legacy_button_darklighter is the only file in ground.

**Comment by Tekaoh** [comment]
Yep, I saw this too. Thanks! I'll see if I can work out a fix...

**Comment by Tekaoh** [comment]
There's a really screwy inconsistency between `datatables/questtask/quest/legacy_button_reb_darklighter.iff` and `string/en/quest/ground/legacy_button_reb_darklighter.stf` and the serverside files. I don't know what the story is there... The strings are (mostly) fixed now, but this (and the imperial versions) should likely be revisited.
